# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Srinath Jayaraman
tagline:          'Personal website'
description:      'Coder, Data Scientist, Poet, Bibliophile'
url:              https://srinathjayaraman.github.io
baseurl:          /

author:
  name:           'Srinath Jayaraman'
  url:            https://srinathjayaraman.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/srinathjayaraman/srinathjayaraman.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
